# Generated by Django 3.1.5 on 2021-02-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210201_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], max_length=200, null=True),
        ),
    ]
